#pragma once

constexpr UINT WM_TAECHANG_RECEIVABLES_COMPLETE = WM_APP + 101;
constexpr UINT ID_TAECHANG_INPUT_EDIT = 41001;
constexpr UINT ID_TAECHANG_OUTPUT_EDIT = 41002;
constexpr UINT ID_TAECHANG_SELECT_INPUT = 41003;
constexpr UINT ID_TAECHANG_SELECT_OUTPUT = 41004;
constexpr UINT ID_TAECHANG_LOAD_RECEIVABLES = 41005;
constexpr UINT ID_TAECHANG_GENERATE_RECEIVABLES = 41006;
constexpr UINT ID_TAECHANG_RESULT_LIST = 41007;
constexpr UINT ID_TAECHANG_PROGRESS = 41008;
constexpr UINT ID_TAECHANG_DETAIL_EDIT = 41009;

constexpr int TAECHANG_MARGIN = 16;
constexpr int TAECHANG_LABEL_WIDTH = 90;
constexpr int TAECHANG_BUTTON_WIDTH = 120;
constexpr int TAECHANG_BUTTON_HEIGHT = 28;
constexpr int TAECHANG_EDIT_HEIGHT = 24;
constexpr int TAECHANG_ROW_GAP = 10;
constexpr int TAECHANG_PROGRESS_HEIGHT = 18;
constexpr int TAECHANG_RESULT_MIN_HEIGHT = 160;

constexpr int TAECHANG_TASK_LOAD_RECEIVABLES = 1;
constexpr int TAECHANG_TASK_GENERATE_RECEIVABLES = 2;

constexpr LPCWSTR TAECHANG_UI_TITLE = L"SageTaechang 미수금 내역서";
constexpr LPCWSTR TAECHANG_UI_INPUT_LABEL = L"Input";
constexpr LPCWSTR TAECHANG_UI_OUTPUT_LABEL = L"Output";
constexpr LPCWSTR TAECHANG_UI_INPUT_BUTTON = L"파일 선택";
constexpr LPCWSTR TAECHANG_UI_OUTPUT_BUTTON = L"폴더 선택";
constexpr LPCWSTR TAECHANG_UI_LOAD_BUTTON = L"미리보기";
constexpr LPCWSTR TAECHANG_UI_GENERATE_BUTTON = L"내역서 생성";
constexpr LPCWSTR TAECHANG_UI_READY = L"대기 중";
constexpr LPCWSTR TAECHANG_UI_RUNNING = L"처리 중";
constexpr LPCWSTR TAECHANG_UI_COMPLETED = L"완료";
constexpr LPCWSTR TAECHANG_UI_FAILED = L"실패";
constexpr LPCWSTR TAECHANG_UI_SELECT_INPUT_TITLE = L"미수금 입력 파일 선택";
constexpr LPCWSTR TAECHANG_UI_SELECT_OUTPUT_TITLE = L"미수금 내역서 저장 폴더 선택";
constexpr LPCWSTR TAECHANG_UI_INPUT_REQUIRED = L"Input 파일을 선택하세요.";
constexpr LPCWSTR TAECHANG_UI_OUTPUT_REQUIRED = L"Output 폴더를 선택하세요.";
constexpr LPCWSTR TAECHANG_UI_EXCEL_FILTER = L"Excel Files (*.xls;*.xlsx)|*.xls;*.xlsx|All Files (*.*)|*.*||";
constexpr LPCWSTR TAECHANG_UI_RESULT_FIELD = L"항목";
constexpr LPCWSTR TAECHANG_UI_RESULT_VALUE = L"값";
constexpr LPCWSTR TAECHANG_UI_RESULT_STATUS = L"Status";
constexpr LPCWSTR TAECHANG_UI_RESULT_FILE = L"File";
constexpr LPCWSTR TAECHANG_UI_RESULT_FOLDER = L"Folder";
constexpr LPCWSTR TAECHANG_UI_RESULT_ERROR = L"Error";
constexpr LPCWSTR TAECHANG_REQUEST_LOAD = L"mfc-receivables-load";
constexpr LPCWSTR TAECHANG_REQUEST_GENERATE = L"mfc-receivables-generate";
