#pragma once

enum SageFontRole {
	SAGE_FONT_CONTROL,
	SAGE_FONT_CONTENT,
	SAGE_FONT_CONTENT_SEMIBOLD,
	SAGE_FONT_TITLE,
	SAGE_FONT_HEADER,
	SAGE_FONT_CAPTION,
	SAGE_FONT_SUMMARY,
	SAGE_FONT_LIST,
	SAGE_FONT_LIST_SEMIBOLD,
	SAGE_FONT_LIST_BOLD,
	SAGE_FONT_LOGO
};

enum SageTextRole {
	SAGE_TEXT_DEFAULT,
	SAGE_TEXT_SECONDARY,
	SAGE_TEXT_PRIMARY,
	SAGE_TEXT_SUCCESS,
	SAGE_TEXT_ERROR,
	SAGE_TEXT_SIDEBAR,
	SAGE_TEXT_SIDEBAR_CATEGORY,
	SAGE_TEXT_MUTED
};

enum SageBackgroundRole {
	SAGE_BG_APP,
	SAGE_BG_PANEL,
	SAGE_BG_SIDEBAR,
	SAGE_BG_STATUS_SUCCESS,
	SAGE_BG_STATUS_WARNING,
	SAGE_BG_STATUS_ERROR,
	SAGE_BG_ACCENT_SURFACE
};

namespace SageUiResources {
	void Create();
	void Destroy();
	CFont* GetFont(SageFontRole nRole);
	HBRUSH GetBrush(SageBackgroundRole nRole);
	COLORREF GetBackgroundColor(SageBackgroundRole nRole);
	COLORREF GetTextColor(SageTextRole nRole);
}
